# NumPy and Pandas
- data analyst & data scientist 
## Data anlyst SQL
- SQL
    - Gold standard
    - Used in corporate setting
    - One shot query
- programmers - MNC
- power bi - charts, visualization

## data scientists
- excel
- line by line (step)
- python - numpy, pandas
- open-source
- scikit
- Visualization libraries

## numpy
- pip install numpy


In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


## Numpy

- good working with arrays - dx 
- performant 
    - internally using C language
- Statistical oriented - mean, mode, std

In [3]:
import numpy as np 
# import line

## short cuts
- `ctrl+alt+enter` -> run the cell
- `shift + enter` -> move to next cell

In [4]:
# creating an array
import numpy as np

marks = np.array([90, 80, 20, 40])

marks_list = [90, 80, 20, 40]
marks_list * 2
marks * 2 # only last line will run with play button

array([180, 160,  40,  80])

In [5]:
dbl_marks = [marks * 2 for marks in marks_list]

print(dbl_marks)

[180, 160, 40, 80]


In [6]:
np.ones(200) # identity matrix | row 
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.arange(10)
np.arange(1, 10) # start, end value 
np.arange(1, 10, 2) # start, end, step


array([1, 3, 5, 7, 9])

In [8]:
np.arange(10) > 5 # boolean output | like a loop 

array([False, False, False, False, False, False,  True,  True,  True,
        True])

## Operations
- multiply, division, addition and subtraction
- don't need a loop
- filter using boolean matrix 

In [9]:
np.arange(10) * 2 # doubles the numbers
np.arange(10) + 2
np.arange(10) / 2
np.arange(10) - 2


array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [10]:
first_ten_nums = np.arange(1, 11)
first_ten_nums[first_ten_nums > 5] # pass list of boolean to FILTER and give new list

array([ 6,  7,  8,  9, 10])

## Task 1
Create a 1..200 numbers and provide a numpy array with all even numbers

In [11]:
nums = np.arange(0, 201, 2)
nums

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200])

## Task 2 
Without the skip of arange

In [12]:
nums = np.arange(1, 201)
nums[nums % 2 == 0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

In [13]:
# random set of integers in a range and concert to list
ages = np.random.randint(18, 60, 10) # start, end, how many
ages
ages_list = ages.tolist()
ages_list

[28, 25, 40, 26, 58, 55, 39, 21, 37, 23]

## Performance
- numpy arrays are 100 times the performance of python list
- %%time

In [14]:
%time

double_ages = [age * 2 for age in ages_list]
print(double_ages)

CPU times: total: 0 ns
Wall time: 0 ns
[56, 50, 80, 52, 116, 110, 78, 42, 74, 46]


## statistical oriented - mean, mode, std
- mean -> average
- mode -> most repeated number
- median -> middle number in the increasing order

In [15]:
marks = np.random.randint(40, 100, 10)
print(marks)
print(marks.mean()) # getting the mean
print(np.mean(marks))

[81 96 59 57 77 43 64 61 67 78]
68.3
68.3


In [16]:
np.median(marks) # finding the median

65.5

In [17]:
np.sum(marks) # sum for total

683

## Task 
invested amount = 1000
rate_of_interest = 0.05
Two years, compound interest
output = 1102.50
10 years -> what happens

In [18]:
invested_amount = 1000
rate_of_interest = 0.05
years = np.arange(1, 11)

# task 1

for year in years:
    investment_balance = 1000 * ((1 + rate_of_interest) ** year)
    print(round(investment_balance,2))

# task 1 using np
years = np.arange(1,11)
yearly_return = 1000 * 1.05 ** years
print(yearly_return)



1050.0
1102.5
1157.63
1215.51
1276.28
1340.1
1407.1
1477.46
1551.33
1628.89
[1050.         1102.5        1157.625      1215.50625    1276.2815625
 1340.09564063 1407.10042266 1477.45544379 1551.32821598 1628.89462678]


In [19]:
# task 2 - slicing 

for year in years:
    investment_balance = 1000 * ((1 + rate_of_interest) ** year)
    if year == 10:
        print(f"The final balance after 10 years is: {round(investment_balance,2)}")

# task 2 using np
years = np.arange(1,11)
yearly_return = 1000 * 1.05 ** years
tenth_year = yearly_return[-1]
print(f"The final balance after 10 years is: {round(tenth_year, 2)}")

The final balance after 10 years is: 1628.89
The final balance after 10 years is: 1628.89


In [20]:
# task 3 
        
for year in years:
    investment_balance = 1000 * ((1 + rate_of_interest) ** year)
    if year == 10:
        final_year_diff = investment_balance - invested_amount
        final_percentage = final_year_diff / 100
        print(f"The amount has increased by {round(final_percentage,2)}%")

# task 3 using np 
years = np.arange(1,11)
yearly_return = 1000 * 1.05 ** years
percentage_increase = ((tenth_year - invested_amount)/ invested_amount) * 100
print(f"The amount has increased by {round(percentage_increase, 2)}%")

The amount has increased by 6.29%
The amount has increased by 62.89%


## Useful methods
- max, min - argmax, argmin
- unique
- string methods


In [21]:
# max and min 

salaries = np.random.randint(1000, 10000, 10)
print(salaries)


[6465 1576 5383 3638 4024 7037 1102 4367 2624 4603]


In [22]:
print(np.max(salaries), np.argmax(salaries))
print(np.min(salaries), np.argmin(salaries))

7037 5
1102 6


In [23]:
# unique

nums = np.random.randint(1, 4, 10)
nums

array([2, 1, 3, 2, 1, 3, 2, 3, 1, 3])

In [24]:
print(np.unique(nums))

uniq_nums = np.unique(nums)
np.flip(uniq_nums) # reverses array

[1 2 3]


array([3, 2, 1])

In [25]:
# string methods
items = np.array([' Apple', 'banana ', 'GRAPE', 'cucumber', 'Pineapple', ' tomato ', 'Orange', ' lemon', 'Kiwi ', 'mango', 'blueberry ', ' raspberry'])
 
# task 1 

item_strip = np.char.strip(items)
item_lower = np.char.lower(item_strip)
final = np.unique(item_lower)
print(final)

np.unique(np.char.lower(np.char.strip(items)))


['apple' 'banana' 'blueberry' 'cucumber' 'grape' 'kiwi' 'lemon' 'mango'
 'orange' 'pineapple' 'raspberry' 'tomato']


array(['apple', 'banana', 'blueberry', 'cucumber', 'grape', 'kiwi',
       'lemon', 'mango', 'orange', 'pineapple', 'raspberry', 'tomato'],
      dtype='<U10')

In [26]:
# task 2
# filtering operations
# create boolean matrix 

final[np.char.startswith(final, 'b')]

array(['banana', 'blueberry'], dtype='<U10')

In [27]:
e_once = final[np.char.count(final, 'e') == 1]
print(e_once)

['apple' 'cucumber' 'grape' 'lemon' 'orange' 'raspberry']


In [28]:
# task 3 
hourly_visitors = [468, 279, 73, 272, 406, 128, 302, 216, 140,82]

array = np.array(hourly_visitors)

daily = np.sum(array)
print(f"Total visitors in the day: {daily}")

peak_hour = np.argmax(array)
print(f"Peak hour: {peak_hour + 1}")

average_visitors = np.average(array)
print(f"Average visitors: {round(average_visitors)} ")

Total visitors in the day: 2366
Peak hour: 1
Average visitors: 237 


## Multi dimensional array

In [29]:
num_3D = np.array([[1, 3, 4],
                  [6, 10, 7],
                  [9, 20, 24]
                  ])

num_3D.shape # gives dimensions of array

(3, 3)

In [30]:
nums1 = np.arange(1,10)
print(nums1)
nums1.shape 

nums1.reshape(3,3) # changes matrix dimensions

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
# value method
num_3x3 = nums1.reshape(3,3) 
np.sum(num_3x3)
np.mean(num_3x3)

5.0

## Axis
- 0 is column 
- 1 is row

In [32]:
# finding value across x or y axis
np.sum(num_3x3, axis=0)


array([12, 15, 18])

In [33]:
num_3x3 + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [34]:
stats = np.random.randint(40, 100, 9)
stats

array([43, 74, 66, 66, 44, 63, 62, 67, 74])

In [35]:
stats_3x3 = stats.reshape(3, 3)
stats_3x3

array([[43, 74, 66],
       [66, 44, 63],
       [62, 67, 74]])

In [36]:
# task - temperature monitor
# find the average temp of every part of the room

sensor1 = np.array([[23, 25, 22],
                    [20, 21, 20],
                    [26, 25, 24]])
 
sensor2 = np.array([[24, 23, 24],
                    [22, 22, 23],
                    [25, 26, 26]])

# task 1

average_temp = (sensor1 + sensor2) / 2
print(average_temp)

# task 2 
across_avg_1 = np.mean(sensor1, axis = 1)
across_avg_2 = np.mean(sensor2, axis= 1)
print(across_avg_1, across_avg_2)

# task 3

avg = (across_avg_1 + across_avg_2) / 2
print(avg)




[[23.5 24.  23. ]
 [21.  21.5 21.5]
 [25.5 25.5 25. ]]
[23.33333333 20.33333333 25.        ] [23.66666667 22.33333333 25.66666667]
[23.5        21.33333333 25.33333333]
